# BMAD Quality Gate - GitHub Actions Workflow
# =============================================
#
# Dit workflow valideert:
# 1. Test requirements (alle verplichte tests aanwezig)
# 2. Invariant coverage (alle invarianten hebben tests)
# 3. Standaard tests (pytest, ruff, etc.)
#
# Installatie:
# Kopieer naar .github/workflows/quality-gate.yml

name: Quality Gate

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  PWSH_VERSION: "7.4"

jobs:
  # =========================================
  # LAAG 3: Enforcement Tools
  # =========================================

  test-gate:
    name: Test Requirements Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nodig voor git diff

      - name: Setup PowerShell
        uses: bjompen/Install-PSModules@v1.1
        with:
          shell: pwsh

      - name: Run Test Gate
        shell: pwsh
        run: |
          if (Test-Path "./tools/test-gate/test-gate.ps1") {
            ./tools/test-gate/test-gate.ps1 -RepoRoot .
          } else {
            Write-Host "test-gate.ps1 not found, skipping..."
            exit 0
          }

  invariant-check:
    name: Invariant Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: bjompen/Install-PSModules@v1.1
        with:
          shell: pwsh

      - name: Run Invariant Check
        shell: pwsh
        run: |
          if (Test-Path "./tools/invariant-check/invariant-check.ps1") {
            ./tools/invariant-check/invariant-check.ps1 -RepoRoot .
          } else {
            Write-Host "invariant-check.ps1 not found, skipping..."
            exit 0
          }

  # =========================================
  # Standard Test Suite
  # =========================================

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check .
        continue-on-error: false

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov

      - name: Run unit tests
        run: |
          pytest tests/unit/ -v --cov=src --cov-report=term-missing || pytest -v

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest

      - name: Run integration tests
        run: |
          if [ -d "tests/integration" ]; then
            pytest tests/integration/ -v
          else
            echo "No integration tests found"
          fi

  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: [unit-tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
            npx playwright install --with-deps
          fi

      - name: Run Playwright tests
        run: |
          if [ -d "tests/e2e" ] || [ -d "e2e" ]; then
            npx playwright test
          else
            echo "No e2e tests found"
          fi

  # =========================================
  # Final Gate
  # =========================================

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [test-gate, invariant-check, lint, unit-tests]
    if: always()

    steps:
      - name: Check all jobs passed
        run: |
          if [ "${{ needs.test-gate.result }}" == "failure" ]; then
            echo "Test Gate failed"
            exit 1
          fi
          if [ "${{ needs.invariant-check.result }}" == "failure" ]; then
            echo "Invariant Check failed"
            exit 1
          fi
          if [ "${{ needs.lint.result }}" == "failure" ]; then
            echo "Lint failed"
            exit 1
          fi
          if [ "${{ needs.unit-tests.result }}" == "failure" ]; then
            echo "Unit Tests failed"
            exit 1
          fi
          echo "All checks passed!"
